name: flutter_test_api_call
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.6.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  logger: ^1.1.0
  shared_preferences: ^2.0.13
  jwt_decoder: ^2.0.1
  cookie_jar: ^4.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
